name: svt_app
description: SVT Car Rental and Taxi Billing App
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.3.1
  timezone: ^0.10.1
  pdf: ^3.11.3
  printing: ^5.14.2

flutter:
  uses-material-design: true
