name: svt_app
description: SVT Car Rental and Taxi Billing App
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5

  pdf: ^3.12.0
  printing: ^5.14.3

  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1

flutter:
  uses-material-design: true
