name: svt_app
description: SVT Car Rental and Taxi Billing App
publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  pdf: ^3.11.3
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
